/*
 * DialogSettings.java
 *
 * Created on November 16, 2004, 3:02 PM
 */

package edu.umiacs.fmm.gui.dialog;
import edu.umiacs.fmm.gui.*;
/**
 *
 * @author  wpwy
 */
public class DialogSettings extends javax.swing.JDialog {
    
    /** Creates new form DialogSettings */
    public DialogSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DialogSettings(){
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSettingContainer = new javax.swing.JPanel();
        lblProblemSize = new javax.swing.JLabel();
        tergetSizeY = new javax.swing.JTextField();
        lblTruncationNum = new javax.swing.JLabel();
        tfTruncationNum = new javax.swing.JTextField();
        lblDummy24 = new javax.swing.JLabel();
        btnSettingReset = new javax.swing.JButton();
        lblDummy25 = new javax.swing.JLabel();
        btnSettingOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfClusterNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblProblemSize1 = new javax.swing.JLabel();
        sourceSizeX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setLocationByPlatform(true);
        setModal(true);

        pnlSettingContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlSettingContainer.setAutoscrolls(true);
        pnlSettingContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSettingContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProblemSize.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblProblemSize.setText("Targets (M):");
        pnlSettingContainer.add(lblProblemSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 45, -1, -1));

        tergetSizeY.setColumns(8);
        tergetSizeY.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tergetSizeY.setText(""+n);
        tergetSizeY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tergetSizeYActionPerformed(evt);
            }
        });
        pnlSettingContainer.add(tergetSizeY, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 43, -1, -1));

        lblTruncationNum.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTruncationNum.setText("Truncation Number (p):");
        pnlSettingContainer.add(lblTruncationNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 75, -1, -1));

        tfTruncationNum.setColumns(8);
        tfTruncationNum.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfTruncationNum.setText(""+truncationNumber);
        pnlSettingContainer.add(tfTruncationNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 75, -1, -1));
        pnlSettingContainer.add(lblDummy24, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 100, 5, 5));

        btnSettingReset.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSettingReset.setText("Reset to default");
        btnSettingReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingResetActionPerformed(evt);
            }
        });
        pnlSettingContainer.add(btnSettingReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 151, -1, -1));
        pnlSettingContainer.add(lblDummy25, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 130, 5, 5));

        btnSettingOK.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSettingOK.setText("OK");
        btnSettingOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingOKActionPerformed(evt);
            }
        });
        pnlSettingContainer.add(btnSettingOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 187, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Clustering Parameter (q):");
        pnlSettingContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 105, -1, -1));

        tfClusterNumber.setColumns(8);
        tfClusterNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfClusterNumber.setText((clusterNumber==-1?"Auto":(""+clusterNumber)));
        pnlSettingContainer.add(tfClusterNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 105, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Enter -1 to autogenerate q.");
        pnlSettingContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 130, -1, -1));

        lblProblemSize1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblProblemSize1.setText("Sources (N):");
        pnlSettingContainer.add(lblProblemSize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 19, -1, -1));

        sourceSizeX.setColumns(8);
        sourceSizeX.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        sourceSizeX.setText(""+n);
        pnlSettingContainer.add(sourceSizeX, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 17, -1, -1));

        getContentPane().add(pnlSettingContainer, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSettingResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingResetActionPerformed
        // TODO add your handling code here:
        n=Constants.DEFAULT_N;
        truncationNumber = Constants.DEFAULT_TRUNCATION_NUMBER;
        tergetSizeY.setText(""+n);
        tfTruncationNum.setText(""+truncationNumber);
    }//GEN-LAST:event_btnSettingResetActionPerformed

    private void btnSettingOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        n = Integer.parseInt(sourceSizeX.getText());
        m = Integer.parseInt(tergetSizeY.getText());
        truncationNumber = Integer.parseInt(tfTruncationNum.getText());
        try {
            this.clusterNumber = Integer.parseInt(tfClusterNumber.getText());
        }catch (Exception e){clusterNumber = -1;}
        
        fireActionListenerActionPerformed(evt);
    }//GEN-LAST:event_btnSettingOKActionPerformed

    private void tergetSizeYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tergetSizeYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tergetSizeYActionPerformed
    
    javax.swing.event.EventListenerList listenerList = new javax.swing.event.EventListenerList();
    
    /**
     * Notifies all registered listeners about the event.
     *
     * @param event The event to be fired
     */
    private void fireActionListenerActionPerformed(java.awt.event.ActionEvent event) {
        
        if (listenerList == null) return;
        Object[] listeners = listenerList.getListenerList();
        for (int i = listeners.length-2; i>=0; i-=2) {
            if (listeners[i]==java.awt.event.ActionListener.class) {
                ((java.awt.event.ActionListener)listeners[i+1]).actionPerformed(event);
            }
        }
    }
    /**
     * Registers ActionListener to receive events.
     * @param listener The listener to register.
     */
    public synchronized void addActionListener(java.awt.event.ActionListener listener) {
        
        if (listenerList == null ) {
            listenerList = new javax.swing.event.EventListenerList();
        }
        listenerList.add(java.awt.event.ActionListener.class, listener);
    }
    
    /**
     * Removes ActionListener from the list of listeners.
     * @param listener The listener to remove.
     */
    public synchronized void removeActionListener(java.awt.event.ActionListener listener) {
        
        listenerList.remove(java.awt.event.ActionListener.class, listener);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogSettings(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     * Getter for property n.
     * @return Value of property n.
     */
    public int getN() {

        return this.n;
    }

    /**
     * Setter for property n.
     * @param n New value of property n.
     */
    public void setN(int n) {

        this.n = n;
    }
    public void setM(int m)
    {
        this.m = m;
    }
    public int getM()
    {
        return m;
    }

    /**
     * Getter for property truncationNumber.
     * @return Value of property truncationNumber.
     */
    public int getTruncationNumber() {

        return this.truncationNumber;
    }

    /**
     * Setter for property truncationNumber.
     * @param truncationNumber New value of property truncationNumber.
     */
    public void setTruncationNumber(int truncationNumber) {

        this.truncationNumber = truncationNumber;
    }

    public int getClusterNumber(){
        return this.clusterNumber;
    }
    public void setClusterNumber(int c){
        this.clusterNumber=c;
    }
    /**
     * Getter for property level.
     * @return Value of property level.
     */
    public int getLevel() {

        return this.level;
    }

    /**
     * Setter for property level.
     * @param level New value of property level.
     */
    public void setLevel(int level) {

        this.level = level;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSettingOK;
    private javax.swing.JButton btnSettingReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDummy24;
    private javax.swing.JLabel lblDummy25;
    private javax.swing.JLabel lblProblemSize;
    private javax.swing.JLabel lblProblemSize1;
    private javax.swing.JLabel lblTruncationNum;
    private javax.swing.JPanel pnlSettingContainer;
    private javax.swing.JTextField sourceSizeX;
    private javax.swing.JTextField tergetSizeY;
    private javax.swing.JTextField tfClusterNumber;
    private javax.swing.JTextField tfTruncationNum;
    // End of variables declaration//GEN-END:variables

    //int threshold = Constants.DEFAULT_THRESHOLD;
    int truncationNumber  = Constants.DEFAULT_TRUNCATION_NUMBER;
    int clusterNumber = Constants.DEFAULT_CLUSTER_NUMBER;
    /**
     * Holds value of property n.
     */
    private int n = Constants.DEFAULT_N;

    /**
     * Holds value of property level.
     */
    private int level = 2;
    
    private int m = Constants.DEFAULT_N;
}
