/*
 * DialogAbout.java
 *
 * Created on November 16, 2004, 12:35 PM
 */

package edu.umiacs.fmm.gui.dialog;

/**
 *
 * @author  wpwy
 */
public class DialogAbout extends javax.swing.JDialog {
    
    /** Creates new form DialogAbout */
    public DialogAbout(){
        super();
        initComponents();
    }
    public DialogAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelLogo = new javax.swing.JLabel();
        panelDialogAboutMain1 = new edu.umiacs.fmm.gui.dialog.PanelDialogAboutMain();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setLocationByPlatform(true);
        setModal(true);
        setName("About this software");
        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umiacs/fmm/gui/resources/logo48x48.gif")));
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelLogo.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        getContentPane().add(jLabelLogo, java.awt.BorderLayout.WEST);

        panelDialogAboutMain1.setPreferredSize(new java.awt.Dimension(454, 256));
        getContentPane().add(panelDialogAboutMain1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-525)/2, (screenSize.height-310)/2, 525, 310);
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogAbout(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private edu.umiacs.fmm.gui.dialog.PanelDialogAboutMain panelDialogAboutMain1;
    // End of variables declaration//GEN-END:variables
    
}
