/*
 * DialogSettings.java
 *
 * Created on November 16, 2004, 3:02 PM
 */

package edu.umiacs.fmm.gui.dialog;
import edu.umiacs.fmm.gui.*;
/**
 *
 * @author  wpwy
 */
public class DialogSettings extends javax.swing.JDialog {
    
    /** Creates new form DialogSettings */
    public DialogSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DialogSettings(){
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSettingContainer = new javax.swing.JPanel();
        lblProblemSize = new javax.swing.JLabel();
        tfProblemSize = new javax.swing.JTextField();
        lblTruncationNum = new javax.swing.JLabel();
        tfTruncationNum = new javax.swing.JTextField();
        lblDummy24 = new javax.swing.JLabel();
        btnSettingReset = new javax.swing.JButton();
        lblDummy25 = new javax.swing.JLabel();
        btnSettingOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfClusterNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setLocationByPlatform(true);
        setModal(true);
        pnlSettingContainer.setLayout(new java.awt.GridBagLayout());

        pnlSettingContainer.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        lblProblemSize.setFont(new java.awt.Font("Dialog", 0, 12));
        lblProblemSize.setText("Problem Size (N):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(lblProblemSize, gridBagConstraints);

        tfProblemSize.setColumns(8);
        tfProblemSize.setFont(new java.awt.Font("Dialog", 0, 12));
        tfProblemSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfProblemSize.setText(""+n);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(tfProblemSize, gridBagConstraints);

        lblTruncationNum.setFont(new java.awt.Font("Dialog", 0, 12));
        lblTruncationNum.setText("Truncation Number (p):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(lblTruncationNum, gridBagConstraints);

        tfTruncationNum.setColumns(8);
        tfTruncationNum.setFont(new java.awt.Font("Dialog", 0, 12));
        tfTruncationNum.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfTruncationNum.setText(""+truncationNumber);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(tfTruncationNum, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlSettingContainer.add(lblDummy24, gridBagConstraints);

        btnSettingReset.setFont(new java.awt.Font("Dialog", 0, 12));
        btnSettingReset.setText("Reset to default");
        btnSettingReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingResetActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(btnSettingReset, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlSettingContainer.add(lblDummy25, gridBagConstraints);

        btnSettingOK.setFont(new java.awt.Font("Dialog", 0, 12));
        btnSettingOK.setText("OK");
        btnSettingOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingOKActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(btnSettingOK, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("Clustering Parameter (q):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(jLabel1, gridBagConstraints);

        tfClusterNumber.setColumns(8);
        tfClusterNumber.setFont(new java.awt.Font("Dialog", 0, 12));
        tfClusterNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfClusterNumber.setText((clusterNumber==-1?"Auto":(""+clusterNumber)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSettingContainer.add(tfClusterNumber, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("Enter -1 to autogenerate q.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlSettingContainer.add(jLabel2, gridBagConstraints);

        getContentPane().add(pnlSettingContainer, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnSettingResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingResetActionPerformed
        // TODO add your handling code here:
        n=Constants.DEFAULT_N;
        truncationNumber = Constants.DEFAULT_TRUNCATION_NUMBER;
        tfProblemSize.setText(""+n);
        tfTruncationNum.setText(""+truncationNumber);
    }//GEN-LAST:event_btnSettingResetActionPerformed

    private void btnSettingOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        n = Integer.parseInt(tfProblemSize.getText());
        truncationNumber = Integer.parseInt(tfTruncationNum.getText());
        try {
            this.clusterNumber = Integer.parseInt(tfClusterNumber.getText());
        }catch (Exception e){clusterNumber = -1;}
    }//GEN-LAST:event_btnSettingOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogSettings(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     * Getter for property n.
     * @return Value of property n.
     */
    public int getN() {

        return this.n;
    }

    /**
     * Setter for property n.
     * @param n New value of property n.
     */
    public void setN(int n) {

        this.n = n;
    }

    /**
     * Getter for property truncationNumber.
     * @return Value of property truncationNumber.
     */
    public int getTruncationNumber() {

        return this.truncationNumber;
    }

    /**
     * Setter for property truncationNumber.
     * @param truncationNumber New value of property truncationNumber.
     */
    public void setTruncationNumber(int truncationNumber) {

        this.truncationNumber = truncationNumber;
    }

    public int getClusterNumber(){
        return this.clusterNumber;
    }
    public void setClusterNumber(int c){
        this.clusterNumber=c;
    }
    /**
     * Getter for property level.
     * @return Value of property level.
     */
    public int getLevel() {

        return this.level;
    }

    /**
     * Setter for property level.
     * @param level New value of property level.
     */
    public void setLevel(int level) {

        this.level = level;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSettingOK;
    private javax.swing.JButton btnSettingReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDummy24;
    private javax.swing.JLabel lblDummy25;
    private javax.swing.JLabel lblProblemSize;
    private javax.swing.JLabel lblTruncationNum;
    private javax.swing.JPanel pnlSettingContainer;
    private javax.swing.JTextField tfClusterNumber;
    private javax.swing.JTextField tfProblemSize;
    private javax.swing.JTextField tfTruncationNum;
    // End of variables declaration//GEN-END:variables

    //int threshold = Constants.DEFAULT_THRESHOLD;
    int truncationNumber  = Constants.DEFAULT_TRUNCATION_NUMBER;
    int clusterNumber = Constants.DEFAULT_CLUSTER_NUMBER;
    /**
     * Holds value of property n.
     */
    private int n = Constants.DEFAULT_N;

    /**
     * Holds value of property level.
     */
    private int level = 2;
}
