/*
 * DialogClickPoints.java
 *
 * Created on August 2, 2005, 1:45 PM
 */

package edu.umiacs.fmm.gui.dialog;
import java.util.*;
import edu.umiacs.fmm.*;
import edu.umiacs.fmm.gui.*;
/**
 *
 * @author  wpwy
 */
public class DialogClickPoints extends javax.swing.JDialog {
    public DialogClickPoints(){
        super();
        initComponents();
    }
    /** Creates new form DialogClickPoints */
    public DialogClickPoints(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonX = new javax.swing.JRadioButton();
        jRadioButtonY = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelCurrLocation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldS = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        layerPointsX = new edu.umiacs.fmm.gui.LayerPoints();
        layerPointsY = new edu.umiacs.fmm.gui.LayerPoints();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("Create ");
        jToolBar1.add(jLabel2);

        buttonGroup1.add(jRadioButtonX);
        jRadioButtonX.setFont(new java.awt.Font("Dialog", 0, 12));
        jRadioButtonX.setSelected(true);
        jRadioButtonX.setText("Sources (X)");
        jToolBar1.add(jRadioButtonX);

        buttonGroup1.add(jRadioButtonY);
        jRadioButtonY.setFont(new java.awt.Font("Dialog", 0, 12));
        jRadioButtonY.setText("Targets (Y)");
        jToolBar1.add(jRadioButtonY);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("at position: ");
        jToolBar1.add(jLabel1);

        jLabelCurrLocation.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelCurrLocation.setText("(1.0000, 1.0000)");
        jLabelCurrLocation.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelCurrLocation.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabelCurrLocation.setPreferredSize(new java.awt.Dimension(100, 14));
        jToolBar1.add(jLabelCurrLocation);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setText("S=");
        jToolBar1.add(jLabel3);

        jTextFieldS.setText("12");
        jToolBar1.add(jTextFieldS);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jLayeredPane1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(512, 512));
        layerPointsX.setColor(java.awt.Color.red);
        layerPointsX.setBounds(0, 0, 512, 512);
        jLayeredPane1.add(layerPointsX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        layerPointsY.setColor(java.awt.Color.blue);
        layerPointsY.setBounds(0, 0, 512, 512);
        jLayeredPane1.add(layerPointsY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        jPanel2.setMinimumSize(new java.awt.Dimension(512, 512));
        jPanel2.setPreferredSize(new java.awt.Dimension(512, 512));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jPanel2.setBounds(0, 0, 512, 512);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelStatus.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelStatus.setText(getCountLabel());
        jPanel1.add(jLabelStatus, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton3);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-520)/2, (screenSize.height-600)/2, 520, 600);
    }
    // </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
// TODO add your handling code here:
        
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
// TODO add your handling code here:
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
// TODO add your handling code here:
        edu.umiacs.fmm.Point p = edu.umiacs.fmm.gui.Util.awtToFmmPoint(evt.getPoint(), this.layerPointsX.getProportion());
        if (this.jRadioButtonX.isSelected()){
            if (!sources.contains(p))
                this.sources.addElement(p);
            this.layerPointsX.setPoints(sources);
            
            this.layerPointsX.repaint();
        }
        else if (this.jRadioButtonY.isSelected()){
            if (!targets.contains(p))
                this.targets.addElement(p);
            this.layerPointsY.setPoints(targets);
            this.layerPointsY.repaint();
        }
        this.updateCountLabel();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.sources = new Vector<Point>();
        targets = new Vector<Point>();
        layerPointsX.setPoints(sources);
        layerPointsY.setPoints(targets);
        layerPointsX.repaint();
        layerPointsY.repaint();
        this.updateCountLabel();
        //this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        this.fireActionListenerActionPerformed(new java.awt.event.ActionEvent(this, 0, "done"));
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
// TODO add your handling code here:
        edu.umiacs.fmm.Point p = edu.umiacs.fmm.gui.Util.awtToFmmPoint(evt.getPoint(), this.layerPointsX.getProportion());
        this.jLabelCurrLocation.setText("("+formatter.format(p.getCoord().real())+", "+formatter.format(p.getCoord().imaginary())+")");
        
    }//GEN-LAST:event_jPanel2MouseMoved
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogClickPoints(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    public String getCountLabel(){
        return "Total: "+sources.size()+" sources and "+targets.size()+" targets";
    }
    public void updateCountLabel(){
        this.jLabelStatus.setText(getCountLabel());
    }
    public Vector<Point> getSources(){
        return sources;
    }
    public Vector<Point> getTargets(){
        return targets;
    }
    public int getS(){
        return Integer.parseInt(this.jTextFieldS.getText());
    }
    private java.text.DecimalFormat formatter = new java.text.DecimalFormat("#.####");
    private Vector<Point> sources = new Vector<Point>();
    private Vector<Point> targets = new Vector<Point>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCurrLocation;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonX;
    private javax.swing.JRadioButton jRadioButtonY;
    private javax.swing.JTextField jTextFieldS;
    private javax.swing.JToolBar jToolBar1;
    private edu.umiacs.fmm.gui.LayerPoints layerPointsX;
    private edu.umiacs.fmm.gui.LayerPoints layerPointsY;
    // End of variables declaration//GEN-END:variables

    /**
     * Utility field used by event firing mechanism.
     */
    private javax.swing.event.EventListenerList listenerList =  null;

    /**
     * Registers ActionListener to receive events.
     * @param listener The listener to register.
     */
    public synchronized void addActionListener(java.awt.event.ActionListener listener) {

        if (listenerList == null ) {
            listenerList = new javax.swing.event.EventListenerList();
        }
        listenerList.add (java.awt.event.ActionListener.class, listener);
    }

    /**
     * Removes ActionListener from the list of listeners.
     * @param listener The listener to remove.
     */
    public synchronized void removeActionListener(java.awt.event.ActionListener listener) {

        listenerList.remove (java.awt.event.ActionListener.class, listener);
    }

    /**
     * Notifies all registered listeners about the event.
     * 
     * @param event The event to be fired
     */
    private void fireActionListenerActionPerformed(java.awt.event.ActionEvent event) {

        if (listenerList == null) return;
        Object[] listeners = listenerList.getListenerList ();
        for (int i = listeners.length - 2; i >= 0; i -= 2) {
            if (listeners[i]==java.awt.event.ActionListener.class) {
                ((java.awt.event.ActionListener)listeners[i+1]).actionPerformed (event);
            }
        }
    }
    
}
